### ISSUE TITLE
Ubuntu 18, tbdialout, sip handler

### ISSUE THREAD

**Issue by Tobida** [tipichris/TBDialOut#12]
Hi,
actually i am using tbdialout 1.8.0pre1 with Ubuntu 18, Thunderbird 68.7.0, with a snom phone. Works. Now i want to switch to a softphone. Ekiga is installed and works fine together with my sip provider, also by using command line with 
`ekiga -c sip:<number>@<provider>`

in TBDialOut i did the setting to 
"userdefinded URL"
and 
`sip:%NUM%@<sipprovder>`
Trying to do a call, i get the message
`sip is not a registered protocol or not allowed in this context`
(not exactly, cause translated from german)
so i checked your wiki-page, found your advice about regisrtering sip and did this (with and without sudo):
`gconftool-2 -s /desktop/gnome/url-handlers/sip/command '/usr/bin/ekiga -c %s' --type String`
But the error message stays the same.
Checking the configuration with
`gconftool-2 -t /desktop/gnome/url-handlers/sip/command`
shows the correct entry.

Any suggestions would be great ...

**Comment by tipichris** [comment]
Don't use userdefined URL in TBDialOut. That is intended for http. Just use sip:

**Comment by Tobida** [comment]
I followed your FAQ:
http://www.oak-wood.co.uk/faq/content/3/19/en/how-do-i-use-tbdialout-with-ekiga.html?highlight=ekiga
Ekiga seems to need more then just a number.
But it doesn't matter: After switchting the settings to "SIP", the error message unfortunately stays the same. So, this is not the reason.

**Comment by tipichris** [comment]
So long since I wrote that part I'd forgetten about Ekiga and full sip URLs.

It seems the way in which URL handlers are configured in Ubuntu has changed. I've just done this, and got somewhere…

Create a file `~/.local/share/applications/sipurl.desktop` and put this in it:

```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Exec=/usr/bin/ekiga -c %u
Name=sip-url
Comment=sip-url handler
Icon=
Categories=Application;Network;
MimeType=x-scheme-handler/sip;
```
I think this is needed because the default ekiga.desktop file does not have the -c %u part in the Exec statement. There may be a more elegant approach involving actions, but just creating a new sipurl.desktop seemed easier.

Then run
`xdg-settings set default-url-scheme-handler sip sipurl.desktop`

For me, that worked, in combination with the custom sip: URL

**Comment by Tobida** [comment]
Whow. That was great help. Thank you, that's the solution.
